name: Hygiene Checks
on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  thret_blog:
    name: Blog Hygiene Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['11']

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3.0.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Test and Build project
        run: mvn clean install -Dspring.profiles.active=test
